// 인증 관련 액션 타입
export const UPDATE_USER = 'UPDATE_USER';

export const SIGN_IN_WITH_EMAIL_REQUEST = 'SIGN_IN_WITH_EMAIL_REQUEST';
export const SIGN_IN_WITH_EMAIL_SUCCESS = 'SIGN_IN_WITH_EMAIL_SUCCESS';
export const SIGN_IN_WITH_EMAIL_FAILED = 'SIGN_IN_WITH_EMAIL_FAILED';

export const SIGN_UP_WITH_EMAIL_REQUEST = 'SIGN_UP_WITH_EMAIL_REQUEST';
export const SIGN_UP_WITH_EMAIL_SUCCESS = 'SIGN_UP_WITH_EMAIL_SUCCESS';
export const SIGN_UP_WITH_EMAIL_FAILED = 'SIGN_UP_WITH_EMAIL_FAILED';

export const SIGN_IN_WITH_FACEBOOK_REQUEST = 'SIGN_IN_WITH_FACEBOOK_REQUEST';
export const SIGN_IN_WITH_FACEBOOK_SUCCESS = 'SIGN_IN_WITH_FACEBOOK_SUCCESS';
export const SIGN_IN_WITH_FACEBOOK_FAILED = 'SIGN_IN_WITH_FACEBOOK_FAILED';

export const SIGN_IN_WITH_GOOGLE_REQUEST = 'SIGN_IN_WITH_GOOGLE_REQUEST';
export const SIGN_IN_WITH_GOOGLE_SUCCESS = 'SIGN_IN_WITH_GOOGLE_SUCCESS';
export const SIGN_IN_WITH_GOOGLE_FAILED = 'SIGN_IN_WITH_GOOGLE_FAILED';

export const SIGN_OUT_REQUEST = 'SIGN_OUT_REQUEST';
export const SIGN_OUT_SUCCESS = 'SIGN_OUT_SUCCESS';
export const SIGN_OUT_FAILED = 'SIGN_OUT_FAILED';


// 게시글 관련 액션 타입
export const ADD_ARTICLE_REQUEST = 'ADD_ARTICLE_REQUEST';
export const ADD_ARTICLE_SUCCESS = 'ADD_ARTICLE_SUCCESS';
export const ADD_ARTICLE_FAILED = 'ADD_ARTICLE_FAILED';


// 게시글리스트 액션 타입
export const GET_ARTICLE_LIST_REQUEST = 'GET_ARTICLE_LIST_REQUEST';
export const GET_ARTICLE_LIST_SUCCESS = 'GET_ARTICLE_LIST_SUCCESS';
export const GET_ARTICLE_LIST_FAILED = 'GET_ARTICLE_LIST_FAILED';

// 게시글 액션 타입
export const GET_ARTICLE_REQUEST = 'GET_ARTICLE_REQUEST';
export const GET_ARTICLE_SUCCESS = 'GET_ARTICLE_SUCCESS';
export const GET_ARTICLE_FAILED = 'GET_ARTICLE_FAILED';

// 댓글 리스트 액션 타입
export const GET_COMMENT_LIST_REQUEST = 'GET_COMMENT_LIST_REQUEST';
export const GET_COMMENT_LIST_SUCCESS = 'GET_COMMENT_LIST_SUCCESS';
export const GET_COMMENT_LIST_FAILED = 'GET_COMMENT_LIST_FAILED';

// 댓글 입력 액션 타입
export const ADD_COMMENT_REQUEST = 'ADD_COMMENT_REQUEST';
export const ADD_COMMENT_SUCCESS = 'ADD_COMMENT_SUCCESS';
export const ADD_COMMENT_FAILED = 'ADD_COMMENT_FAILED';

export const OPEN_LOGIN_MODAL = 'OPEN_LOGIN_MODAL';
export const CLOSE_LOGIN_MODAL = 'CLOSE_LOGIN_MODAL';


// 좋아요 관련 액션 타입
export const GET_LIKE_REQUEST = 'GET_LIKE_REQUEST';
export const GET_LIKE_SUCCESS = 'GET_LIKE_SUCCESS';
export const GET_LIKE_FAILED = 'GET_LIKE_FAILED';

// 게시글 관련 액션 타입
export const LIKE_ARTICLE_REQUEST = 'LIKE_ARTICLE_REQUEST';
export const LIKE_ARTICLE_SUCCESS = 'LIKE_ARTICLE_SUCCESS';
export const LIKE_ARTICLE_FAILED = 'LIKE_ARTICLE_FAILED';