
export const UPDATE_USER = 'UPDATE_USER';

export const SIGN_IN_WITH_EMAIL_REQUEST = 'SIGN_IN_WITH_EMAIL_REQUEST';
export const SIGN_IN_WITH_EMAIL_SUCCESS = 'SIGN_IN_WITH_EMAIL_SUCCESS';
export const SIGN_IN_WITH_EMAIL_FAILED = 'SIGN_IN_WITH_EMAIL_FAILED';

export const SIGN_UP_WITH_EMAIL_REQUEST = 'SIGN_UP_WITH_EMAIL_REQUEST';
export const SIGN_UP_WITH_EMAIL_SUCCESS = 'SIGN_UP_WITH_EMAIL_SUCCESS';
export const SIGN_UP_WITH_EMAIL_FAILED = 'SIGN_UP_WITH_EMAIL_FAILED';

export const SIGN_IN_WITH_FACEBOOK_REQUEST = 'SIGN_IN_WITH_FACEBOOK_REQUEST';
export const SIGN_IN_WITH_FACEBOOK_SUCCESS = 'SIGN_IN_WITH_FACEBOOK_SUCCESS';
export const SIGN_IN_WITH_FACEBOOK_FAILED = 'SIGN_IN_WITH_FACEBOOK_FAILED';

export const SIGN_IN_WITH_GOOGLE_REQUEST = 'SIGN_IN_WITH_GOOGLE_REQUEST';
export const SIGN_IN_WITH_GOOGLE_SUCCESS = 'SIGN_IN_WITH_GOOGLE_SUCCESS';
export const SIGN_IN_WITH_GOOGLE_FAILED = 'SIGN_IN_WITH_GOOGLE_FAILED';

export const SIGN_OUT_REQUEST = 'SIGN_OUT_REQUEST';
export const SIGN_OUT_SUCCESS = 'SIGN_OUT_SUCCESS';
export const SIGN_OUT_FAILED = 'SIGN_OUT_FAILED';
